#!/usr/bin/perl -W

require "sfile";
require "sfile_bw";

$name=$sfile::fullpath;

$name_bw=$sfile_bw::fn;


$ext=".avi";
$f_name=$name.$ext;


$f_cam1="/video/zhostovo/camera1/$f_name";

$f_cam3="/video/zhostovo/camera3/$f_name";

$f_bw_karg="/video/karg/$name_bw";

$f_bw_penta="/video/penta/$name_bw";


#if ((-e $f_cam1) && (-e $f_cam3) && (-e $f_bw_penta) && (-e $f_bw_karg)) {
#print "Ok";
#print "\n";
#}

#else {
#print "some went wrong";
#print "\n";
#}

    if (-e $f_cam1) {
$cam1=1;
$cm1="cam1_ok";
}
    else {
$cam1=0;
$cm1="cam1_error";
}

    if (-e $f_cam3) {
$cam3=1;
$cm3="cam3_ok";
}
    else {
$cam3=0;
$cm3="cam3_error";
}

    if (-e $f_bw_penta) {
$f_bw_penta=1;
$cmpenta="bw_penta_ok";
}
    else {
$f_bw_penta=0;
$cmpenta="bw_penta_error";
}

    if (-e $f_bw_karg) {
$f_bw_karg=1;
$cmkarg="bw_karg_ok";
}
    else {
$f_bw_penta=0;
$cmkarg="bw_karg_error";
}



$summ=$cam1+$cam3+$f_bw_penta+$f_bw_karg;

    $dt=localtime;
@mas=split(" ",$dt);

     open(my $filo, '>', 'report.txt');

#print $filo $mas[1],' ',$mas[2],' ', $mas[3], "\n";

print $filo $mas[1],' ', $mas[2],' ', "\n";
@tm=split(":", $mas[3]);
$tm=join(">",$tm[0],$tm[1],$tm[2]);
print $filo $tm, "\n";

if ($summ != 4) {
print $filo "something went wrong", "\n";
print $filo $cm1, "\n";
print $filo $cm3, "\n";
print $filo $cmpenta, "\n";
print $filo $cmkarg, "\n";
print $filo "\n";
}

else {
print $filo "ok", "\n";
print $filo $cm1, "\n";
print $filo $cm3, "\n";
print $filo $cmpenta, "\n";
print $filo $cmkarg. "\n";
print $filo "\n";

}

close $filo;

system "/bin/cat /etc/mysc/ch_video/report.txt | /usr/sbin/ssmtp n.v.shadrin"

